### ISSUE TITLE
feat: implement Sonyflake

### ISSUE THREAD

**Issue by mikkpokk** [calebdw/laraflake#1]
Package `php-snowflake` has Sonyflake under the hood as well. It would be great to implement Sonyflake with laraflake package as well.

> Sonyflake has the following advantages and disadvantages: The lifetime (174 years) is longer than that of Snowflake (69 years) It can work in more distributed machines (2^16) than Snowflake (2^10) It can generate 2^8 IDs per 10 msec at most in a single machine/thread (slower than Snowflake)

**Comment by calebdw** [comment]
Hello!

Thanks for the suggestion---do you see a need for both Snowflakes and Sonyflakes to both be used in the same application or should the application just configure one or the other?

The easiest thing to do would just be to swap out the specific implementation in the container

**Comment by mikkpokk** [comment]
I believe it's one or another per application. Sonyflake benefits are it's longer lifetime and ability to run in more distributed machines without overlaps, having a side-effect it has a bit slower proccessing time compared to Snowflake.

I think it would be neat to have ability to instruct Laravel use one or another based on configuration parameter. That way it would remove an overhead to bootstrap both services at the same time.

**Comment by calebdw** [comment]
That's along the same lines as I was thinking, done! :partying_face:
